"""v4

Revision ID: 3afabca4cd31
Revises: 4c193ce922a8
Create Date: 2022-02-25 00:46:28.094990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3afabca4cd31'
down_revision = '4c193ce922a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tos_agree_date', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('privacy_agree_date', sa.DateTime(), nullable=False))
    op.drop_column('user', 'tos_agree')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tos_agree', mysql.DATETIME(), nullable=False))
    op.drop_column('user', 'privacy_agree_date')
    op.drop_column('user', 'tos_agree_date')
    # ### end Alembic commands ###
